import './batch-test.js';
import './compose-test.js';
import './each-test.js';
import './filter-test.js';
import './flatten-test.js';
import './iterator-test.js';
import './map-test.js';
import './range-test.js';
import './series-test.js';